### ISSUE TITLE
[Feature]: Prettier in `pre-commit`

### ISSUE THREAD

**Issue by Anselmoo** [Anselmoo/spectrafit#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Missing Feature

Prettier in `pre-commit`

### Possible Solution

https://prettier.io/docs/en/precommit.html

```yaml
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "" # Use the sha or tag you want to point at
  hooks:
    - id: prettier
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
