### ISSUE TITLE
[Feature]: Add Sourcery to `pre-commit`

### ISSUE THREAD

**Issue by Anselmoo** [Anselmoo/spectrafit#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Missing Feature

https://docs.sourcery.ai/Guides/Getting-Started/Pre-Commit/

### Possible Solution

```yaml
repos:
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v0.13.0
    hooks:
      - id: sourcery
        # The best way to use Sourcery in a pre-commit hook:
        # * review only changed lines:
        # * omit the summary
        args: [--diff=git diff HEAD, --no-summary]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
