### ISSUE TITLE
improving readability of fit output reporting 

### ISSUE THREAD

**Issue by josephzsombor** [Anselmoo/spectrafit#804]
One issue affecting the user-friendliness of spectrafit-jupyter is the readability of the output of each fit. The user specifies parameters for each peak in the model, such as the "max", "min", and "value" of "amplitude", "center", "fwhmg", and "fwhml" for a pseudovoigt function, for instance. 

Upon running one fitting procedure, the information most useful to the user in assessing the validity of a **given iteration** of the fit is the best value of each parameter of the function (i.e., "best_value" of "value", "amplitude", "center", "fwhmg", and "fwhml"). It would be helpful to quickly see only those results upon running the solver, that way the user can quickly assess whether one value is running up against its restrictions or whether the fit is approaching convergence.

One useful feature might be to generate as an output a text file containing the initial model with the value of each parameter adjusted to the best_value resulting from the fit.

**Comment by Anselmoo** [comment]
So, for _each iteration_ the best values should be shown up?

**Comment by josephzsombor** [comment]
I don't think it's important to see the best values of each iteration in the final report, but it would be useful to print a table with the best values after each iteration... this way the user can see if one value is running up against its limit, for example (which can be a sign of over-fitting).

For the final report, a useful feature would be to generate a final_model file resembling the initial_model file... this way, the user can give the final_model file to someone and they can easily re-start from that final_model.

-Joseph
________________________________

**Comment by Anselmoo** [comment]
With the command `show_peaks=True`

```python
spn.solver_model(initial_model=initial_model, show_plot=False, show_peaks=True)
```

Peaks, according to the iteration, will be already printed. These tables will generally become extremely crowded due to the amount of data.

 
<img width="1097" alt="image" src="https://github.com/Anselmoo/spectrafit/assets/13209783/5e21d215-efd3-4dcc-b3ec-194f38a1c6da">

> For the final report, a useful feature would be to generate a final_model file resembling the initial_model file... this way, the user can give the final_model file to someone and they can easily re-start from that final_model.

The report already contains information of the initial model:

```toml

[peaks.1.pseudovoigt.amplitude]
max = 4
min = 0
vary = true
value = 1

[peaks.1.pseudovoigt.center]
max = 5470
min = 5460
vary = true
value = 5468
```

as well as the comparison between the best and the initial model

```toml
[fit_insights.variables.pseudovoigt_fwhmg_3]
init_value = 1
model_value = 0.10000000837664919
best_value = 0.10000000837664919

[fit_insights.variables.pseudovoigt_fwhml_3]
init_value = 1
model_value = 3.7499977334701127
best_value = 3.7499977334701127

[fit_insights.variables.gaussian_amplitude_4]
init_value = 3
model_value = 0.6090009741875487
best_value = 0.6090009741875487

[fit_insights.variables.gaussian_center_4]
init_value = 5478
model_value = 5477.92439530641
best_value = 5477.92439530641
```

However, the initial model is not the starting model. If needed, this type of information will be automatically saved in the cmd mode as `*.csv`. https://github.com/Anselmoo/spectrafit/blob/main/Examples/example_7_errors.csv

If required, we will implement it in the notebook mode.
